---
abstract: ' '
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Test2::V1: '0'
configure_requires:
  Affix: '0'
  CPAN::Meta: '2.150012'
  Exporter: '5.57'
  ExtUtils::Helpers: '0.028'
  ExtUtils::Install: '0'
  ExtUtils::InstallPaths: '0.002'
  File::Basename: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '2.36'
  JSON::PP: '2'
  Path::Tiny: '0'
  perl: v5.40.0
dynamic_config: 1
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150012'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Parataxis
no_index:
  directory: []
  file: []
  namespace: []
  package: []
provides:
  Acme::Parataxis:
    file: lib/Acme/Parataxis.pm
    version: v0.0.1
  Acme::Parataxis::Future:
    file: lib/Acme/Parataxis.pm
  Acme::Parataxis::Root:
    file: lib/Acme/Parataxis.pm
requires:
  Affix: '0'
  File::Basename: '0'
  File::Spec: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: v0.0.1
x_ignore:
  - .tidyallrc
  - .gitignore
  - .clang-format
  - .github/**
  - ROADMAP.md
x_plugins:
  - GitHubActions
  - GitHubActions
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
