---
abstract: 'A dangerous hybrid of cooperative fibers and preemptive native threads'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  Test2::V1: '0'
configure_requires:
  Affix: v1.2.6
  Affix::Build: '0'
  CPAN::Meta: '2.150012'
  Exporter: '5.57'
  ExtUtils::Helpers: '0.028'
  ExtUtils::Install: '0'
  ExtUtils::InstallPaths: '0.002'
  File::Basename: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '2.36'
  JSON::PP: '2'
  Path::Tiny: '0'
  Test2::V1: '0'
  perl: v5.40.0
dynamic_config: 1
generated_by: 'App::mii v1.0.0, CPAN::Meta::Converter version 2.150013'
keywords: []
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Parataxis
no_index:
  directory: []
  file: []
  namespace: []
  package: []
provides:
  Acme::Parataxis:
    file: lib/Acme/Parataxis.pm
    version: v0.1.1
  Acme::Parataxis::Actor:
    file: lib/Acme/Parataxis/Actor.pm
    version: v0.1.1
  Acme::Parataxis::CancellationToken:
    file: lib/Acme/Parataxis/CancellationToken.pm
    version: v0.1.1
  Acme::Parataxis::Channel:
    file: lib/Acme/Parataxis/Channel.pm
    version: v0.1.1
  Acme::Parataxis::Compat:
    file: lib/Acme/Parataxis/Compat.pm
    version: v0.1.1
  Acme::Parataxis::Driver:
    file: lib/Acme/Parataxis/Driver.pm
    version: v0.1.1
  Acme::Parataxis::Driver::IOAsync:
    file: lib/Acme/Parataxis/Driver/IOAsync.pm
    version: v0.1.1
  Acme::Parataxis::Driver::Mojo:
    file: lib/Acme/Parataxis/Driver/Mojo.pm
    version: v0.1.1
  Acme::Parataxis::Error:
    file: lib/Acme/Parataxis/Error.pm
    version: v0.1.1
  Acme::Parataxis::Error::Cancelled:
    file: lib/Acme/Parataxis/Error.pm
    version: v0.1.1
  Acme::Parataxis::Error::Nursery:
    file: lib/Acme/Parataxis/Error.pm
    version: v0.1.1
  Acme::Parataxis::Error::STM_Retry:
    file: lib/Acme/Parataxis/Error.pm
    version: v0.1.1
  Acme::Parataxis::Error::Supervisor:
    file: lib/Acme/Parataxis/Error.pm
    version: v0.1.1
  Acme::Parataxis::Error::Timeout:
    file: lib/Acme/Parataxis/Error.pm
    version: v0.1.1
  Acme::Parataxis::Future:
    file: lib/Acme/Parataxis/Future.pm
    version: v0.1.1
  Acme::Parataxis::Generator:
    file: lib/Acme/Parataxis/Generator.pm
    version: v0.1.1
  Acme::Parataxis::Local:
    file: lib/Acme/Parataxis/Local.pm
    version: v0.1.1
  Acme::Parataxis::Nursery:
    file: lib/Acme/Parataxis/Nursery.pm
    version: v0.1.1
  Acme::Parataxis::RateLimiter:
    file: lib/Acme/Parataxis/RateLimiter.pm
    version: v0.1.1
  Acme::Parataxis::Semaphore:
    file: lib/Acme/Parataxis/Semaphore.pm
    version: v0.1.1
  Acme::Parataxis::Semaphore::Guard:
    file: lib/Acme/Parataxis/Semaphore.pm
  Acme::Parataxis::Signal:
    file: lib/Acme/Parataxis/Signal.pm
    version: v0.1.1
  Acme::Parataxis::Stream:
    file: lib/Acme/Parataxis/Stream.pm
    version: v0.1.1
  Acme::Parataxis::Supervisor:
    file: lib/Acme/Parataxis/Supervisor.pm
    version: v0.1.1
  Acme::Parataxis::Sync:
    file: lib/Acme/Parataxis/Sync.pm
    version: v0.1.1
  Acme::Parataxis::Sync::Barrier:
    file: lib/Acme/Parataxis/Sync/Barrier.pm
    version: v0.1.1
  Acme::Parataxis::Sync::Mutex:
    file: lib/Acme/Parataxis/Sync/Mutex.pm
    version: v0.1.1
  Acme::Parataxis::Sync::Mutex::Guard:
    file: lib/Acme/Parataxis/Sync/Mutex.pm
  Acme::Parataxis::Sync::Once:
    file: lib/Acme/Parataxis/Sync/Once.pm
    version: v0.1.1
  Acme::Parataxis::Sync::RwLock:
    file: lib/Acme/Parataxis/Sync/RwLock.pm
    version: v0.1.1
  Acme::Parataxis::Sync::RwLock::Guard:
    file: lib/Acme/Parataxis/Sync/RwLock.pm
  Acme::Parataxis::Sync::WaitGroup:
    file: lib/Acme/Parataxis/Sync/WaitGroup.pm
    version: v0.1.1
  Acme::Parataxis::TVar:
    file: lib/Acme/Parataxis/TVar.pm
    version: v0.1.1
  Acme::Parataxis::Ticker:
    file: lib/Acme/Parataxis/Ticker.pm
    version: v0.1.1
requires:
  Affix: v1.2.6
  File::Basename: '0'
  File::Spec: '0'
resources:
  bugtracker: https://github.com/sanko/Acme-Parataxis.pm/issues
  homepage: https://github.com/sanko/Acme-Parataxis.pm
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/Acme-Parataxis.pm.git
version: v0.1.1
x_ignore:
  - .tidyallrc
  - .gitignore
  - .clang-format
  - .github/**
  - ROADMAP.md
x_plugins:
  - GitHubActions
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
